### ISSUE TITLE
yarn setup gives error

### ISSUE THREAD

**Issue by imskr** [EmaSuriano/gatsby-starter-mate#382]
Running `yarn setup` and filling details gives: 

```
Writing config file...
TypeError: envfile.stringifySync is not a function
    at /home/skr/github/skr/bin/setup.js:52:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by fcatus** [comment]
I am having the exact same problem.

OS: MacOS
yarn version: 1.22.4
Gatsby version: 2.23.3

```
Writing config file...
TypeError: envfile.stringifySync is not a function
    at /Users/user/mate-portfolio/bin/setup.js:52:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
✨  Done in 67.66s.
```

**Comment by EmaSuriano** [comment]
Hey thanks for reporting! Should be fixed in this commit --> https://github.com/EmaSuriano/gatsby-starter-mate/commit/5c5fddc6131d02d5bfd77f6a9294a3cce8cd7db5
