### ISSUE TITLE
Not able to complete yarn setup command

### ISSUE THREAD

**Issue by Meet-shah** [EmaSuriano/gatsby-starter-mate#416]
When i run the yarn setup command and paste the api keys it gives following error:

```
The following 1 errors and 0 warnings occurred:

11:13:70 - Error: Status: 403 - Forbidden - Message: The access token you sent could not be found or is invalid. - Request ID: 19f8ca41f0674308b5056cbbfb9d3223

Stored the detailed error log file at:
C:\Users\HP\Desktop\mate-portfolio\contentful-import-error-log-gtvr7c3o44yv-2020-07-01T11-13-13.json
(node:3036) UnhandledPromiseRejectionWarning: ContentfulMultiError: Errors occured
    at C:\Users\HP\Desktop\mate-portfolio\node_modules\contentful-import\dist\index.js:202:28
    at tryCatcher (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\HP\Desktop\mate-portfolio\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
(node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 105.62s  ~.
```

**Comment by EmaSuriano** [comment]
Hello @Meet-shah, please check the video I recorded where I showed from where you have to take the token from Contentful --> https://www.youtube.com/watch?v=YviWsypJF9c

**Comment by Meet-shah** [comment]
Thanks !! i
