### ISSUE TITLE
Failing at yarn setup

### ISSUE THREAD

**Issue by periwinkleFTW** [EmaSuriano/gatsby-starter-mate#711]
UPDATE: I confused the preview token with management token.

SUGGESTION: Include the clarification that API page with `Space ID` and `Content Delivery API - access token` do not show the management token. Management token must be generated in the Content management tab.

I made a new space on contentful but when I run the `yarn setup` after entering the info it throws an error:
```
Writing config file...
Importing content into your Contentful ...
┌──────────────────────────────────────────────────┐
│ The following entities are going to be imported: │
├─────────────────────────────────┬────────────────┤
│ Content Types                   │ 3              │
├─────────────────────────────────┼────────────────┤
│ Editor Interfaces               │ 3              │
├─────────────────────────────────┼────────────────┤
│ Entries                         │ 8              │
├─────────────────────────────────┼────────────────┤
│ Assets                          │ 4              │
├─────────────────────────────────┼────────────────┤
│ Locales                         │ 1              │
├─────────────────────────────────┼────────────────┤
│ Webhooks                        │ 0              │
├─────────────────────────────────┼────────────────┤
│ Tags                            │ 0              │
└─────────────────────────────────┴────────────────┘
  ✔ Validating content-file
  ✔ Initialize client (1s)
  ✖ Checking if destination space already has any content and retrieving it
 (1s)
    → AccessTokenInvalid: Status: 403 - Forbidden - Message: The access tok
…
    Apply transformations to source data
    Push content to destination space


The following 1 errors and 0 warnings occurred:

18:10:11 - Error: Status: 403 - Forbidden - Message: The access token you sent could not be found or is invalid. - Request ID: e32a4ecba10bf0e758f2e2cc915637a3

Stored the detailed error log file at:
/Users/andreyf/Projects/andrey-landing-page/andrey-lander/contentful-import-error-log-locbsooimm6e-2021-03-04T18-10-65.json
(node:93745) UnhandledPromiseRejectionWarning: ContentfulMultiError: Errors occurred
    at /Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/contentful-import/dist/index.js:202:28
    at tryCatcher (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andreyf/Projects/andrey-landing-page/andrey-lander/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:93745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:93745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 18.41s.
```

**Comment by EmaSuriano** [comment]
Hey, have you checked the YouTube video with the explanation? Maybe you are
sending the wrong value. Let me know if it works!

periwinkleFTW <notifications@github.com> schrieb am Fr., 5. März 2021,
02:14:

**Comment by periwinkleFTW** [comment]
I have update the post that I confused the preview token with management token. Since starter was asking for access code and 2 API key I assumed that the page that showed access code and 2 API keys had all the information i needed. It took some googling to realize the the 3rd API had to be created in an another tab

**Comment by EmaSuriano** [comment]
Glad to hear that you figure it out 🙌
